version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - ./docker/app/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini:ro
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates:ro
      - ./src:/app:ro
    working_dir: /var/www/html
    depends_on:
      - app
    ports:
      - "${NGINX_PORT:-8080}:8080"
    environment:
      FCGI_HOST: app:9000
